# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: slim-mustache 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "slim-mustache"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Michel Benevento"]
  s.date = "2015-06-25"
  s.description = "use a ~tilde to generate {{mustache}} syntax"
  s.email = "michelbenevento@yahoo.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/slim/mustache.rb",
    "lib/slim/mustache/filter.rb",
    "lib/slim/mustache/grammar.rb",
    "lib/slim/mustache/parser.rb",
    "slim-mustache.gemspec",
    "test/helper.rb",
    "test/test_slim-mustache.rb"
  ]
  s.homepage = "http://github.com/beno/slim-mustache"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "mustache/handlebars support for slim"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<slim>, ["~> 3.0"])
      s.add_development_dependency(%q<minitest>, ["~> 5.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<slim>, ["~> 3.0"])
      s.add_dependency(%q<minitest>, ["~> 5.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<slim>, ["~> 3.0"])
    s.add_dependency(%q<minitest>, ["~> 5.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

